<?php

/**
 * @file
 * The module file for the test_shoutbox module
 */

use Drupal\views\ViewExecutable;


/**
 * Implements hook_theme().
 */
function test_shoutbox_theme($existing, $type, $theme, $path) {
  return [
    'shoutbox_answers_list' => [
      'variables' => ['shoutbox' => NULL],
      'path' => drupal_get_path('module', 'test_shoutbox') .'/template',
      'template' => 'shoutbox_answers_list',
      'file' => 'test_shoutbox.theme.inc'
    ],
    'shoutbox_entity' => [
      'render element' => 'elements',
      'path' => drupal_get_path('module', 'test_shoutbox') .'/template',
      'template' => 'shoutbox',
      'file' => 'test_shoutbox.theme.inc'
    ],
    'shoutbox_answer' => [
      'render element' => 'elements',
      'path' => drupal_get_path('module', 'test_shoutbox') .'/template',
      'template' => 'shoutbox_answer',
      'file' => 'test_shoutbox.theme.inc'
    ]
  ];
}


/**
 * Implements hook_views_pre_render().
 *
 *  - alter the title for our answers administration view
 *    per shoutbox
 */
function test_shoutbox_views_pre_render(ViewExecutable $view) {
  if($view->id() == 'answers_to_shoutbox' && $view->current_display == 'page_2') {
    $shoutbox = \Drupal\test_shoutbox\Entity\Shoutbox::load($view->args[0]);
    $view->setTitle($shoutbox->label());
  }
}